CREATE TABLE IF NOT EXISTS messages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    sender VARCHAR(64) NOT NULL,
    content VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO messages (sender, content) VALUES
    ('alice', 'PLAINTEXT_SECRET_HELLO_FROM_ALICE'),
    ('bob',   'PLAINTEXT_SECRET_HELLO_FROM_BOB');

GRANT ALL PRIVILEGES ON demo.* TO 'demo'@'%';
FLUSH PRIVILEGES;
